blacklist = ["lazygit", "claude", "scratch"]
# [default_session]
# startup_command = "fastfetch"
#
# [[session]]
# name = "Mobile ðŸ“²"
# path = "~/Projects/mobile/"
# startup_command = "tmux new-window -n 'server' "
#
# [[session]]
# name = "tmux config"
# path = "~/c/dotfiles/.config/tmux"
# startup_command = "nvim tmux.conf"
