[[mgr.prepend_keymap]]
on   = "<Enter>"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = "<Backspace>"
run  = "leave"
desc = "Go up one directory"

[[mgr.prepend_keymap]]
on   = [ "g", "." ]
run  = "cd ~/dotfiles"
desc = "Goto to ~/dotfiles"

[[mgr.prepend_keymap]]
on   = "p"
run  = "plugin smart-paste"
desc = "Paste into the hovered directory or CWD"
